export const FEAT_NAME_LIST = [
  "Ability Score Improvement",
  "Aberrant Dragonmark",
  "Actor",
  "Adept of the Black Robes",
  "Adept of the Red Robes",
  "Adept of the White Robes",
  "Alert",
  "Artificer Initiate",
  "Athlete",
  "Baleful Scion",
  "Bountiful Luck",
  "Cartomancer",
  "Charger",
  "Chef",
  "Cohort of Chaos",
  "Crossbow Expert",
  "Crusher",
  "Defensive Duelist",
  "Divinely Favored",
  "Dragon Fear",
  "Dragon Hide",
  "Drow High Magic",
  "Dual Wielder",
  "Dungeon Delver",
  "Durable",
  "Dwarven Fortitude",
  "Eldritch Adept",
  "Elemental Adept",
  "Elven Accuracy",
  "Ember of the Fire Giant",
  "Fade Away",
  "Fey Teleportation",
  "Fey Touched",
  "Fighting Initiate",
  "Flames of Phlegethos",
  "Fury of the Frost Giant",
  "Gift of the Chromatic Dragon",
  "Gift of the Gem Dragon",
  "Gift of the Metallic Dragon",
  "Grappler",
  "Great Weapon Master",
  "Guile of the Cloud Giant",
  "Gunner",
  "Healer",
  "Heavily Armored",
  "Heavy Armor Master",
  "Infernal Constitution",
  "Initiate of High Sorcery",
  "Inspiring Leader",
  "Keen Mind",
  "Keenness of the Stone Giant",
  "Knight of the Crown",
  "Knight of the Rose",
  "Knight of the Sword",
  "Lightly Armored",
  "Linguist",
  "Lucky",
  "Mage Slayer",
  "Magic Initiate",
  "Martial Adept",
  "Medium Armor Master",
  "Metamagic Adept",
  "Mobile",
  "Moderately Armored",
  "Mounted Combatant",
  "Observant",
  "Orcish Fury",
  "Piercer",
  "Planar Wanderer",
  "Poisoner",
  "Polearm Master",
  "Prodigy",
  "Resilient",
  "Revenant Blade",
  "Ritual Caster",
  "Rune Shaper",
  "Savage Attacker",
  "Scion of the Outer Planes",
  "Second Chance",
  "Sentinel",
  "Shadow Touched",
  "Sharpshooter",
  "Shield Master",
  "Skill Expert",
  "Skilled",
  "Skulker",
  "Slasher",
  "Soul of the Storm Giant",
  "Spell Sniper",
  "Squire of Solamnia",
  "Squat Nimbleness",
  "Strike of the Giants",
  "Svirfneblin Magic",
  "Tavern Brawler",
  "Telekinetic",
  "Telepathic",
  "Tough",
  "Vigor of the Hill Giant",
  "War Caster",
  "Weapon Master",
  "Wood Elf Magic"
];

export default FEAT_NAME_LIST;
